- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks :
  - name: Deploy Docker Container
    command: docker run -itd -p 8084:8081 veereshvishu/health-insure-me:3.0
