apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbapp
spec:
  selector:
    matchLabels:
      app: sbapp
  replicas: 3
  template:
    metadata:
      labels:
        app: sbapp
    spec:
      containers:
      - name: sbapp
        image: veereshvishu/medicure:latest
        imagePullPolicy: Always
        ports:
        - name: sbapp
          containerPort: 8082
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sbapp-nodeport
  labels:
    app: sbapp
spec:
  type: NodePort
  selector:
    app: sbapp
  ports:
  - name: http
    port: 8082
    targetPort: 8082
    nodePort: 30082 # You can change this (range: 30000–32767)
